"""Sample-record diagnostic for correlated classical beliefs.

An explicitly easy affine distribution, NOT a quantum advantage or inference
benchmark. Exact integer Walsh transforms check every parity query. Independent
samples are generated by a direct classical algorithm. No quantum state is run.
"""
from __future__ import annotations
import argparse
from fractions import Fraction
import itertools
import json
import math
from pathlib import Path
import numpy as np


def encode(free: np.ndarray, groups: int) -> np.ndarray:
    """Each 3 independent bits become a 4-bit block with even parity."""
    free = np.asarray(free, dtype=np.int64)
    result = np.zeros_like(free)
    for j in range(groups):
        a = (free >> (3*j)) & 7
        parity = (a ^ (a >> 1) ^ (a >> 2)) & 1
        result |= (a | (parity << 3)) << (4*j)
    return result


def walsh(counts: np.ndarray) -> np.ndarray:
    a = np.asarray(counts, dtype=np.int64).copy()
    n = len(a)
    if n == 0 or n & (n-1):
        raise ValueError('Power-of-two input length required.')
    step = 1
    while step < n:
        block = a.reshape(-1, 2*step)
        left = block[:, :step].copy()
        right = block[:, step:].copy()
        block[:, :step] = left + right
        block[:, step:] = left - right
        step *= 2
    return a


def exact_character_is_one(mask: np.ndarray, groups: int) -> np.ndarray:
    out = np.ones_like(mask, dtype=bool)
    for j in range(groups):
        block = (mask >> (4*j)) & 15
        out &= (block == 0) | (block == 15)
    return out


def fraction(x: int, y: int) -> str:
    return str(Fraction(int(x), int(y)))


def run() -> dict:
    # Independently check encoding and the Walsh calculation on small cases.
    tiny = 0
    for groups in (1, 2):
        support = encode(np.arange(1 << (3*groups)), groups)
        dim = 1 << (4*groups)
        counts = np.bincount(support, minlength=dim)
        got = walsh(counts)
        expected = exact_character_is_one(np.arange(dim), groups).astype(np.int64)*len(support)
        if not np.array_equal(got, expected):
            raise AssertionError('Analytic character expectation failed.')
        for mask in range(dim):
            direct = sum(1 if (int(x) & mask).bit_count() % 2 == 0 else -1 for x in support)
            if got[mask] != direct:
                raise AssertionError('Walsh transform differs from direct parity sum.')
            tiny += len(support)
    groups = 5
    variables = 4*groups
    dim = 1 << variables
    support_size = 1 << (3*groups)
    rng = np.random.default_rng(2026092608)
    samples = encode(rng.integers(0, support_size, size=8192, dtype=np.int64), groups)
    masks = np.arange(dim, dtype=np.int64)
    exact_one = exact_character_is_one(masks, groups)
    support = encode(np.arange(support_size), groups)
    records = []
    for m in (1024, 4096, 8192):
        counts = np.bincount(samples[:m], minlength=dim)
        coefficients = walsh(counts)
        discrepancy = np.abs(coefficients - m*exact_one.astype(np.int64))
        max_sign_error_num = int(discrepancy.max())
        # Query f_S=(1+chi_S)/2 lies in [0,1], so its error is half the character error.
        tv_num = int(np.abs(support_size*counts[support] - m).sum())
        unique = int(np.count_nonzero(counts))
        empirical_all_constraints = int(np.sum(counts[support]))
        if empirical_all_constraints != m:
            raise AssertionError('Sample left the specified posterior support.')
        max_one = max(int(discrepancy[1 << i]) for i in range(variables))
        max_two = max(int(discrepancy[(1 << i) | (1 << j)])
                      for i,j in itertools.combinations(range(variables), 2))
        # Every within-block parity constraint is true exactly for every sample.
        if any(int(coefficients[15 << (4*j)]) != m for j in range(groups)):
            raise AssertionError('Four-way correlation lost by the joint sample record.')
        records.append(dict(samples=m, stored_bits=m*variables,
            stored_bytes_bitpacked=m*variables//8,
            parity_queries_checked=dim,
            max_sign_expectation_error=fraction(max_sign_error_num,m),
            max_parity_probability_error=fraction(max_sign_error_num,2*m),
            max_single_bit_probability_error=fraction(max_one,2*m),
            max_pair_parity_probability_error=fraction(max_two,2*m),
            empirical_total_variation=fraction(tv_num,2*m*support_size),
            empirical_total_variation_decimal=tv_num/(2*m*support_size),
            unique_sampled_configurations=unique,
            posterior_mass_on_observed_support=fraction(unique,support_size),
            empirical_probability_of_observed_support='1',
            observed_support_gap=fraction(support_size-unique,support_size),
            four_way_constraints_empirical_probability='1'))
    epsilon, delta = .05, .05
    sufficient = math.ceil(math.log(2*dim/delta)/(2*epsilon*epsilon))
    # A rare extra condition admits exactly one of the 32768 initially allowed worlds.
    alpha = Fraction(1,support_size)
    no_hit = float((1-alpha)**8192)
    # Evaluate this probability independently via log1p.
    if abs(no_hit-math.exp(8192*math.log1p(-1/support_size)))>1e-12:
        raise AssertionError('Missing-event calculation failed.')
    return dict(scope='Classical sample-record demonstration; no hard inference, new theorem, LLM, native inference solver or quantum performance claim.',
        model=dict(variables=variables, independent_even_parity_blocks=groups,
                   prior='Independent fair bits', evidence='Every disjoint four-bit block has even parity',
                   evidence_probability='1/32', posterior_support=support_size,
                   classical_sampler='Three independent bits per block, plus their XOR as the fourth.',
                   all_single_and_pair_marginals='Exactly the same as independent fair bits',
                   true_all_constraints_probability='1',
                   independent_marginals_all_constraints_probability='1/32',
                   true_four_bit_constraint_probability='1',
                   independent_marginals_four_bit_constraint_probability='1/2'),
        seed=2026092608,numpy_version=np.__version__,small_direct_parity_summands_checked=tiny,
        records=records,
        uniform_bound=dict(function_family='All even-parity predicates on arbitrary subsets of the twenty bits',
                           number_of_functions=dim, epsilon=epsilon, delta=delta,
                           sufficient_independent_samples=sufficient,
                           scope='Hoeffding plus finite union bound, not a posterior construction guarantee or proof from the observed errors.'),
        future_evidence_control=dict(additional_condition='One specified full posterior configuration',
              posterior_probability=str(alpha), samples=8192, chance_record_contains_no_match=no_hit,
              scope='No arbitrary later-conditioning guarantee. Known direct sampler remains easy.'))


if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('--output', type=Path, required=True)
    args = p.parse_args()
    report=run()
    with args.output.open('x',encoding='utf-8') as f:
        json.dump(report,f,indent=2,sort_keys=True)
        f.write('\n')
    print(json.dumps(report,indent=2,sort_keys=True))
